export const GET_NAMES_REQUEST = "GET_NAMES_REQUEST";
export const GET_NAMES_SUCCESS = "GET_NAMES_SUCCESS";
export const GET_NAMES_FAIL = "GET_NAMES_FAIL";

export const POST_NAME_REQUEST = "POST_NAME_REQUEST";
export const POST_NAME_SUCCESS = "POST_NAME_SUCCESS";
export const POST_NAME_FAIL = "POST_NAME_FAIL";